source "https://rubygems.org"

ruby "3.3.0"

gem "rails", "~> 7.1.0"
gem "sqlite3", "~> 1.7"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
end
